### ISSUE TITLE
tshark raise an error : 'Some fields aren't valid:  '

### ISSUE THREAD

**Issue by 3wh1te** [Thijsvanede/FlowPrint#10]
![image](https://user-images.githubusercontent.com/19612068/94110659-93a64e80-fe75-11ea-9175-0ebf585dc89a.png)

`
tshark: Some fields aren't valid:
        ssl.handshake.certificate
`
Is the command  in reader.py is right?
That's my tshark version.
![image](https://user-images.githubusercontent.com/19612068/94111048-1d561c00-fe76-11ea-9e3b-719b6a3defce.png)

**Comment by Thijsvanede** [comment]
Thanks for notifying me!

Indeed, it seems that tshark version 3+ changed the naming convention from `ssl.handshake.certificate` to `tls.handshake.certificate`. I have pushed a fix for this on the latest Github version of FlowPrint. Now the reader performs a quick check on the version number and adapts the command accordingly.

Unfortunately, the latest linux release of tshark is still at version 2. Quick tests showed the fix works for tshark 3, but I haven't been able to test this completely. Could you let me know if this works, if so I will also add the fix to the `pip` version later today.

**Comment by 3wh1te** [comment]
I tested the new reader in my enviroment just now and it worked very well.
```
if __name__ == '__main__':
    reader = Reader()
    reader.read('rbxlook.pcap')
```
![image](https://user-images.githubusercontent.com/19612068/94125855-7f6c4c80-fe89-11ea-8fb8-81791759de5e.png)

**Comment by Thijsvanede** [comment]
Thanks for checking this. The new `pip` version also contains the fix.
