### ISSUE TITLE
TypeError: 'Flow' object is not iterable

### ISSUE THREAD

**Issue by izmcm** [Thijsvanede/FlowPrint#11]
**Describe the bug**
Hello, I'm trying run flowprint in a particular dataset but I get an error in flowprint.py (line 206):
`matches = list(set().union(*[lookup.get(x, set()) for x in fingerprint]))`

The error says **"TypeError: 'Flow' object is not iterable"**

**To Reproduce**
I just copied the sample code that was made available and run in my own dataset

```
preprocessor = Preprocessor(verbose=True)
X, y = preprocessor.process(files = pcaps,
                            labels = labels)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

flowprint = FlowPrint(
    batch       = 300,
    window      = 30,
    correlation = 0.1,
    similarity  = 0.9
)

flowprint.fit(X_train, y_train)
y_recognize = flowprint.recognize(X_test)
```

**Expected behavior**
I believe that the error should not happen

**Screenshots**
Here you can see X_test I'm sending and the error:

![image](https://user-images.githubusercontent.com/27749679/95267324-62316980-080b-11eb-9164-f08dc43e66d3.png)

**Additional context**
I installed flowprint from the command line with `pip install flowprint`. I'm using macOS 10.15.5 to run the code and my dataset consists of data from 5 applications in .pcap format. I'm using Python 3.7.9, TShark 3.0.3

Thank you for your attention! :D

**Comment by Thijsvanede** [comment]
Hi izmcm,

You are completely correct, this example is incorrect.
To be precise, the methods `recognize` and `detect` should not get `Flow` objects as input, but should be given `Fingerprint` objects. This is incorrectly documented in the example, so I will fix this. Please see the documentation of [flowprint.recognize()](https://flowprint.readthedocs.io/en/latest/reference/flowprint.html#app-recognition). I see that the documentation of [flowprint.detect()](https://flowprint.readthedocs.io/en/latest/reference/flowprint.html#unseen-app-detection) is also incorrect, so I'll fix this as well.

A quick working example for you is the following:
```python
from flowprint.preprocessor  import Preprocessor
from flowprint.flowprint     import FlowPrint
from sklearn.model_selection import train_test_split

import numpy as np

if __name__ == "__main__":

    pcaps  = ['<pcap.file>']
    labels = ['label']

    # Load data
    preprocessor = Preprocessor(verbose=True)
    X, y = preprocessor.process(files = pcaps, labels = labels)

    # Split into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

    # Create FlowPrint object
    flowprint = FlowPrint(
        batch       = 300,
        window      = 30,
        correlation = 0.1,
        similarity  = 0.9
    )

    # IMPORTANT: FIRST CREATE FINGERPRINTS
    # Create fingerprints for test
    fp_test = flowprint.fingerprinter.fit_predict(X_test)

    # Fit flowprint with training and testing samples
    flowprint.fit(X_train, y_train)

    # IMPORTANT: HERE WE USE THE FINGERPRINTS INSTEAD OF THE FLOWS
    y_recognize = flowprint.recognize(fp_test)
```

Currently, we don't have a nice method of creating clean fingerprints, so I am working to add a clean `flowprint.fingerprint()` method. I'll update you on this issue when everything is fixed. Probably later today.

**Comment by Thijsvanede** [comment]
I have updated the documentation and added a `flowprint.fingerprint()` method. If you follow the documentation at [flowprint.readthedocs.io](https://flowprint.readthedocs.io/en/latest/usage/code.html) everything should work properly.

Thanks again for letting me know of this bug and if you have any other questions or find incorrectly documented examples or bugs please let me know.

**Comment by izmcm** [comment]
Thank you very much! :D
