### ISSUE TITLE
 A question about per-device fingerprinting 

### ISSUE THREAD

**Issue by mrz8** [Thijsvanede/FlowPrint#19]
I have a question regarding the implementation of the fingerprinting technique in the code you shared.
 In the article, you mentioned that the fingerprint should be generated separately for each device because identifying apps on a  per-device basis assists in limiting the amount of dynamic behavior. However, when I reviewed the code you kindly shared, I noticed that the code does not seem to follow this approach.

Could you please provide some insights to help me understand this discrepancy? Is there something I may have missed or misunderstood?

**Comment by Thijsvanede** [comment]
The data that was available to us was already split per device, so there was no need for us to implement the device splitting technique ourselves. If you want to split network traffic per device, you could use the `Flow.src` parameter (assuming that during a capture each device has a unique and constant IP address).

**Comment by mrz8** [comment]
Thank you for your response. I already evaluated your method on our dataset without separating the traffic by device. But the results were still outstanding:)
