### ISSUE TITLE
Request for Raw PCAP Files of ReCon and ReCon Extended Datasets

### ISSUE THREAD

**Issue by zhangzw16** [Thijsvanede/FlowPrint#20]
Hello,

Firstly, I'd like to commend the team for the exceptional work on this project. The insights and results presented in the paper are truly commendable.

I'm reaching out to inquire if there's a repository or location where I can access the raw PCAP files for both the ReCon and ReCon Extended datasets mentioned in your paper. Having access to these files would greatly assist in further research and analysis.

Thank you for your time and consideration. I look forward to your response.

**Comment by Thijsvanede** [comment]
Hi zhangzw16,

Thank you for your interest. Please reach out to David Choffnes (his email is in our paper), he manages the ReCon datasets.
