### ISSUE TITLE
Problem about store the fingerprints into one .json file

### ISSUE THREAD

**Issue by C1air3** [Thijsvanede/FlowPrint#6]
As shown in  [flowprint.readthedocs.io](https://flowprint.readthedocs.io/en/latest/), when I try to use the command line tool with this command (I have already transform one`.pcap` file into flow and store it in `d:\flows.p`) :

`python -m flowprint --read d:\flows.p --fingerprint d:\fingerprints.json`

I got an error :

`Traceback (most recent call last):`
  `File "C:\Users\clairel\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\clairel\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\FlowPrint-master\FlowPrint-master\flowprint\__main__.py", line 233, in <module>
    fingerprint(flowprint, args)
  File "D:\FlowPrint-master\FlowPrint-master\flowprint\__main__.py", line 92, in fingerprint`
    `flowprint.save(outfile)`
  `File "D:\FlowPrint-master\FlowPrint-master\flowprint\flowprint.py", line 319, in save`
    `for fp in fingerprints or self.fingerprints]`
  `File "D:\FlowPrint-master\FlowPrint-master\flowprint\flowprint.py", line 319, in <listcomp>`
    `for fp in fingerprints or self.fingerprints]`
  `File "D:\FlowPrint-master\FlowPrint-master\flowprint\fingerprint.py", line 114, in to_dict`
    `'certificates': self.certificates,`
  `File "D:\FlowPrint-master\FlowPrint-master\flowprint\fingerprint.py", line 99, in certificates`
    `return sorted([x  for x in self if not isinstance(x, tuple)])`
`TypeError: '<' not supported between instances of 'NoneType' and 'int'`

The version of python is Python 3.7.6.

Is there something wrong? Or I made some mistakes?

**Comment by Thijsvanede** [comment]
I am also able to reproduce the error using commands
```
python3 -m flowprint --pcaps <file.pcap> --write flows.p
python3 -m flowprint --read flows.p --fingerprint fingerprints.json
```

I will check where the bug is and fix it. I'll let you know once I pushed the fix.

**Comment by C1air3** [comment]
> I am also able to reproduce the error using commands
> 
> ```
> python3 -m flowprint --pcaps <file.pcap> --write flows.p
> python3 -m flowprint --read flows.p --fingerprint fingerprints.json
> ```
> 
> I will check where the bug is and fix it. I'll let you know once I pushed the fix.

okay! Thanks :D

**Comment by Thijsvanede** [comment]
The problem occurred when a fingerprint contains some flows with certificates and some flows without. Originaly a None value was stored as a certificate, but this is now removed. The latest GitHub version should now be fixed, and I'll include the fix in the next pip release as well. Thanks for notifying me of the bug and please let me know if you run into any other problems!

**Comment by Thijsvanede** [comment]
Digging a bit deeper, I also see there was an import statement missing. This should be fixed in the latest GitHub version as well.

**Comment by C1air3** [comment]
> The problem occurred when a fingerprint contains some flows with certificates and some flows without. Originaly a None value was stored as a certificate, but this is now removed. The latest GitHub version should now be fixed, and I'll include the fix in the next pip release as well. Thanks for notifying me of the bug and please let me know if you run into any other problems!

It works, I can store one fingerprint into a .json file now. Thanks！lol
